apiVersion: v2
name: emby
type: application

description: Your personal media on any device. Bringing all of your home videos, music, and photos together into one place has never been easier. Your personal Emby Server automatically converts and streams your media on-the-fly to play on any device.

version: 1.3.2
appVersion: "4.8.11.0"

home: https://emby.media
icon: https://github.com/pmoscode-helm/emby/raw/main/assets/logo.png
maintainers:
  - email: info@pmoscode.de
    name: pmoscode
    url: https://pmoscode.de

sources:
  - https://emby.media/

annotations:
  artifacthub.io/images: |
    - name: Emby
      image: emby/embyserver:4.8.11.0
      platforms:
        - linux/amd64
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: Source
      url: https://github.com/pmoscode-helm/emby
    - name: support
      url: https://github.com/pmoscode-helm/emby/issues
  artifacthub.io/maintainers: |
    - name: pmoscode
      email: info@pmoscode.de