apiVersion: v1
kind: Service
metadata:
  name: {{ include "emby.fullname" . }}-headless
  labels:
    {{- include "emby.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "LoadBalancer" }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "emby.selectorLabels" . | nindent 4 }}
